# Generated by Django 4.2.13 on 2024-07-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_serv', models.CharField(max_length=20)),
                ('precio', models.CharField(max_length=11)),
                ('plazo_entrega', models.CharField(max_length=20)),
                ('descripcion_servicio', models.CharField(max_length=500)),
            ],
        ),
    ]
