# Generated by Django 4.2.13 on 2024-07-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller1', '0003_mecanico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='especialidad_me',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
